#let heading-line(body) = align(center, text(weight: "bold", size: 21pt, body))
#v(-1cm)
#heading-line[#text(font: "Helvetica")[Stichiertonen]]
#v(-.5cm)
#image("heer_ik_roep_t1_first_sys.cropped.svg", width: 100%)
#image("heer_ik_roep_t2_first_sys.cropped.svg", width: 100%)
#image("heer_ik_roep_t3_first_sys.cropped.svg", width: 100%)
#image("heer_ik_roep_t4_first_sys.cropped.svg", width: 100%)
#image("heer_ik_roep_t5_first_sys.cropped.svg", width: 100%)
#image("heer_ik_roep_t6_first_sys.cropped.svg", width: 100%)
#image("heer_ik_roep_t7_first_sys.cropped.svg", width: 100%)
#image("heer_ik_roep_t8_first_sys.cropped.svg", width: 100%)
